// Draws src/assets/rune-pattern.svg, the faint pattern behind the tab pages: rune-like marks in
// the style of the owner's reference image (stacked chevrons, crossed staves, dots, diamonds,
// arrows), one per cell of a seamless tile. Seeded, so a rerun gives the same tile.
// Run with `node scripts/rune-pattern.mjs`; the tile's size on screen is set in TabBar.module.scss.
import { writeFileSync } from 'node:fs';

const COLS = 8;
const ROWS = 8;
const CELL = 36;
/** Mark size relative to its drawing below (about 22 units tall), varied a little per mark. */
const SCALE = 0.9;
const STROKE = 2.8;

// A zero-length stroke with round caps draws a dot.
const dot = (x, y) => `M${x} ${y}h0`;
const marks = {
  chevrons: 'M-7-1L0-8L7-1M-7 7L0 0L7 7',
  vees: 'M-6-10L0-5L6-10M-6-3L0 2L6-3M-6 4L0 9L6 4',
  vee: 'M-8-9L0 9L8-9',
  peak: 'M-8 9L0-9L8 9',
  cross: `M-6-6L6 6M6-6L-6 6${dot(0, -11)}${dot(0, 11)}`,
  crosses: 'M-5-11L5-1M5-11L-5-1M-5 1L5 11M5 1L-5 11',
  stave: 'M0-11V11',
  dagger: 'M0-11V11M-6-5H6',
  bars: 'M0-11V11M-6-4H6M-6 3H6',
  dots: `${dot(0, -8)}${dot(0, 0)}${dot(0, 8)}`,
  diamond: `M0-8L7 0L0 8L-7 0Z${dot(0, 0)}`,
  arrow: 'M0 11V-10M-6-4L0-10L6-4',
  zigzag: 'M-9 5L-4.5-5L0 5L4.5-5L9 5',
  peakDot: `M-7 2L0-6L7 2${dot(0, 8)}`,
  staveCross: 'M0-11V11M-7-7L7 7M7-7L-7 7',
  veeDot: `M-7-2L0 6L7-2${dot(0, -9)}`,
  twoDots: `${dot(0, -5)}${dot(0, 5)}`,
  peaks: 'M-7 1L0-6L7 1M-7 9L0 2L7 9M-7-7L0-14L7-7',
};
const names = Object.keys(marks);

// mulberry32
let seed = 0x5e7a1;
function random() {
  seed = (seed + 0x6d2b79f5) | 0;
  let t = seed;
  t = Math.imul(t ^ (t >>> 15), t | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}

const grid = [];
const uses = [];
for (let row = 0; row < ROWS; row++) {
  grid.push([]);
  for (let col = 0; col < COLS; col++) {
    // No mark repeats its neighbour above or to the left.
    let name;
    do {
      name = names[Math.floor(random() * names.length)];
    } while (name === grid[row - 1]?.[col] || name === grid[row][col - 1]);
    grid[row].push(name);
    const x = col * CELL + CELL / 2 + (random() * 4 - 2);
    const y = row * CELL + CELL / 2 + (random() * 4 - 2);
    const angle = Math.round(random() * 10 - 5);
    const scale = (SCALE + random() * 0.1).toFixed(2);
    uses.push(
      `<use href="#${name}" transform="translate(${x.toFixed(1)} ${y.toFixed(1)}) rotate(${angle}) scale(${scale})"/>`,
    );
  }
}

const size = COLS * CELL;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
<!-- Generated by scripts/rune-pattern.mjs. -->
<defs>
${names.map((name) => `<path id="${name}" d="${marks[name]}"/>`).join('\n')}
</defs>
<g fill="none" stroke="#000" stroke-width="${STROKE}" stroke-linecap="round" stroke-linejoin="round">
${uses.join('\n')}
</g>
</svg>
`;
writeFileSync(new URL('../src/assets/rune-pattern.svg', import.meta.url), svg);
console.log(`rune-pattern.svg: ${svg.length} bytes`);
